name: file_gallery
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 图片视频选择器
  image_picker: 1.0.4

  # 仿微信图片视频选择器
  wechat_assets_picker: 8.7.1

  # 文件选择器
  file_picker: 8.0.0+1

  # 视频播放
  # flutter sdk版本不支持时应用不能编译 且没有错误信息
  video_player: 2.7.2

  photo_view: 0.14.0

  # 动态权限
  permission_handler: 11.0.1

  # http 请求库
  dio: 5.3.3

  # 屏幕旋转
  auto_orientation: 2.3.1

  path_provider: 2.1.1

#  # 本地Office文档预览
#  flutter_filereader: 2.2.0
  # 本地应用打开文件
  # sdk<29 manifest添加tools:remove="android:requestLegacyExternalStorage"
  open_file: 3.3.2

  flutter_image_compress: 2.0.2
  video_compress: 3.1.2
  device_info_plus: 9.1.2

# 基本组件
#  common:
#    git:
#      url: https://github.com/itsmagical/common.git
#      url: https://github.com/yy1234/common.git
#      url: git@github.com:yy1234/common.git
#      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - packages/file_gallery/images/file_type_word.png
    - packages/file_gallery/images/file_type_excel.png
    - packages/file_gallery/images/file_type_pdf.png
    - packages/file_gallery/images/file_type_ppt.png
    - packages/file_gallery/images/file_type_txt.png
    - packages/file_gallery/images/file_type_unknown.png
    - packages/file_gallery/images/video_player_pause.png
    - packages/file_gallery/images/video_player_start.png
    - packages/file_gallery/images/status_error.png

  # To add assets to your package, add an assets section, like this:
#   assets:
#     - images/a_dot_burr.jpeg
#     - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
